default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: Autograph
  password: '9043'
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: Autograph_development

production:
  <<: *default
  database: Autograph_production
